package ws.lumo.ai;

import com.fasterxml.jackson.annotation.JsonCreator;
/**
 * Defines the possible roles in a chat conversation, following the convention
 * used by many large language models.
 */
public enum Role {
    /** A message sent by the end-user. */
    USER,
    /** A message generated by the AI model. */
    ASSISTANT,
    /** A message providing instructions or context to the AI model, not visible to the user. */
    SYSTEM;

    @JsonCreator
    public static Role fromString(String value) {
        if (value == null) {
            return null;
        }
        return Role.valueOf(value.toUpperCase());
    }
}