package ws.lumo.api.history;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import ws.lumo.ai.ChatMessage;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Represents a single, complete conversation thread from any adapter.
 * This document is created when a conversation starts and is updated
 * as the conversation progresses.
 */
@Document("conversation_history")
@Data
@NoArgsConstructor
public class ConversationHistory {

    /**
     * A unique identifier for the conversation session.
     * For chat, this is generated by the client. For email, this could be the thread ID.
     */
    @Id
    private String sessionId;

    /**
     * The ID of the adapter that handled this conversation.
     */
    private String adapterId;

    /**
     * The timestamp when the conversation started.
     */
    private Instant startTime;

    /**
     * The timestamp of the last message in the conversation.
     */
    private Instant lastUpdateTime;

    /**
     * The context length used for this conversation, copied from the adapter configuration.
     */
    private Integer contextLength;

    /**
     * The number of times this conversation has been escalated.
     */
    private int escalationCount = 0;

    /**
     * The list of all escalation IDs generated during this conversation.
     */
    private List<String> escalationIds = new ArrayList<>();

    /**
     * The full list of messages in the conversation.
     */
    private List<ChatMessage> messages = new ArrayList<>();

    public ConversationHistory(String sessionId, String adapterId, Integer contextLength) {
        this.sessionId = sessionId;
        this.adapterId = adapterId;
        this.contextLength = contextLength;
        this.startTime = Instant.now();
        this.lastUpdateTime = this.startTime;
    }

    public void addMessage(ChatMessage message) {
        this.messages.add(message);
        this.lastUpdateTime = Instant.now();
    }
}