package ws.lumo.api.ontology;

import ws.lumo.ai.ChatMessage;
import ws.lumo.api.provider.AdapterConfig;

import java.util.Map;
import java.util.List;
import java.util.Optional;

/**
 * A service for querying ontologies to enrich AI prompts.
 */
public interface OntologyQueryService {
    /**
     * Prepares a request to generate a SPARQL query based on the user's query.
     *
     * @param userQuery The natural language query from the user.
     * @param history   The full conversation history.
     * @param config    The configuration of the active adapter.
     * @return An Optional containing a request object for SPARQL generation, or empty if not applicable.
     */
    Optional<SparqlQueryRequest> prepareSparqlQuery(String userQuery, List<ChatMessage> history, AdapterConfig config);

    /**
     * Generates SPARQL queries based on AI-generated criteria.
     *
     * @param request The request containing the prompt and other necessary data.
     * @param adapterId The ID of the adapter.
     * @return An Optional containing a list of SPARQL query criteria strings, or empty if generation failed.
     */
    Optional<List<String>> generateSparqlQueriesFromCriteria(SparqlQueryRequest request, String adapterId);

    /**
     * Executes a list of SPARQL queries and extracts product names from the results.
     *
     * @param sparqlQueries The list of SPARQL queries to execute.
     * @param ontologyDto The OntologyDto representing the current ontology.
     * @param adapterId The ID of the adapter.
     * @return A list of product names found.
     */
    List<String> executeQueryAndGetProductNames(List<String> sparqlQueries, OntologyDto ontologyDto, String adapterId);

    /**
     * Executes a list of SPARQL queries and extracts vector IDs from the results.
     *
     * @param criteria The list of criteria maps generated by the AI.
     * @param ontologyDto The OntologyDto representing the current ontology.
     * @param adapterId The ID of the adapter.
     * @return A list of vector IDs found.
     */
    List<String> executeQueryAndGetVectorIds(List<Map<String, Object>> criteria, OntologyDto ontologyDto, String adapterId);
}